name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0 # Bypass husky commit hook for CI

jobs:
  gravity:
    name: Gravity
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20]
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Run Gravity
        run: npm run gravityci './dist/**/*''
        env:
          GRAVITY_TOKEN: ${{ secrets.GRAVITY_TOKEN }}
