name: Run Tests
on: [push]

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  SKIP_INSTALL_SIMPLE_GIT_HOOKS: 1 # Skip installing simple-git-hooks

jobs:
  test:
    name: Tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20]
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run Unit tests
        run: pnpm run test:unit:ci
      - name: Run E2E tests
        env:
          VITE_ACCESS_TOKEN: ${{ secrets.VITE_ACCESS_TOKEN }}
          VITE_OAUTH_TOKEN: ${{ secrets.VITE_OAUTH_TOKEN }}
          VITE_SPACE_ID: ${{ vars.VITE_SPACE_ID }}
        run: pnpm run build && pnpm run test:e2e
